version: '3.8'

services:
  auth_service:
    build: ./auth_service
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://postgres:password@postgres/dbname
    volumes:
      - ./logs:/app/logs
    depends_on:
      - postgres
    command: sh -c "sleep 5 && uvicorn app.main:app --host 0.0.0.0 --port 8000"

  transaction_service:
    build: ./transaction_service
    ports:
      - "8001:8001"
    environment:
      - DATABASE_URL=postgresql://postgres:password@postgres/dbname
    volumes:
      - ./logs:/app/logs
    depends_on:
      - postgres
    command: sh -c "sleep 5 && uvicorn app.main:app --host 0.0.0.0 --port 8001"

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: dbname
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - ./data/db:/var/lib/postgresql/data

  alembic_auth:
    build: ./auth_service
    environment:
      - DATABASE_URL=postgresql://postgres:password@postgres/dbname
      - ALEMBIC_CONFIG=auth_service/alembic/alembic.ini
    depends_on:
      - postgres
    command: ["sh", "-c", "dockerize -wait tcp://postgres:5432 -timeout 60s alembic upgrade head"]

  alembic_transaction:
    build: ./transaction_service
    environment:
      - DATABASE_URL=postgresql://postgres:password@postgres/dbname
      - ALEMBIC_CONFIG=transaction_service/alembic/alembic.ini
    depends_on:
      - postgres
    command: ["sh", "-c", "dockerize -wait tcp://postgres:5432 -timeout 60s alembic upgrade head"]



